# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  # desc "Runs all the tests"
  # lane :test do
  #   gradle(task: "test")
  # end

  # desc "Submit a new Beta Build to Crashlytics Beta"
  # lane :beta do
  #   gradle(task: "clean assembleRelease")
  #   crashlytics
  
  #   # sh "your_script.sh"
  #   # You can also use other beta testing services here
  # end

  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   gradle(task: "clean assembleRelease")
  #   upload_to_play_store
  # end

desc "Deploy a new QA build to APPCenter"
lane :upload_appcenter do
  # Here we are using the CircleCI job number
  # for the build number
  increment_build_number(
    build_number: "$CIRCLE_BUILD_NUM"
  )

  build_number = number_of_commits()
  Dir.chdir "../.." do
  sh("flutter", "pub", "get")
  sh("flutter", "clean")
  sh("flutter", "build", "appbundle", "--build-number=#{build_number}")

  # Set up the required information to upload the
  # app binary to VS App Center
  appcenter_upload(
    api_token: ENV[VS_API_TOKEN],
    owner_name: "bandeirapbdaniel@gmail.com",
    owner_type: "user",
    app_name: "SecretWall"
  )
# lane :beta do
#   end
#   upload_to_play_store(track: 'beta', aab: '../build/app/outputs/bundle/release/app.aab')
# end
end
